# Generated by Django 4.1.1 on 2022-09-06 21:56

from django.db import migrations, models
import staffs.models


class Migration(migrations.Migration):

    dependencies = [
        ("staffs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="image",
            field=models.ImageField(null=True, upload_to=staffs.models.image_file_path),
        ),
    ]
