# Generated by Django 4.1.1 on 2022-09-10 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("lesson", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="attendanceandgrades", name="groupjournal",),
        migrations.AddField(
            model_name="attendanceandgrades",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="att_and_grades",
                to="lesson.group",
            ),
        ),
    ]
